#template
library(shiny)


ui <- fluidPage(
  headerPanel('US Census Data - Income Predictor'),
  sidebarPanel(
   sliderInput(inputId = "num",
               label = "choose age",
               value =25, min = 17, max = 90),
   selectInput("variable", "Workclass:",
               c("State Gov" = "State-gov",
                 "Federal gov" = "Federal-gov",
                 "Local gov" = "Local-gov",
                 "Never worked" = "Never-worked",
                 "Private" = "Private",
                 "Self emp inc" = "Self-emp-inc",
                 "Self emp not inc" = "Self-emp-not-inc",
                 "Without pay" = "Without-pay")),
   selectInput("Variable", "Education:",
               c("Preschool" = "Preschool",
                 "1st-4th" = "1st-4th",
                 "5th-6th" = "5th-6th",
                 "7th-8th" = "7th-8th",
                 "9th" = "9th",
                 "10th" = "10th",
                 "12th" = "12th",
                 "HS-grad" = "HS-grad",
                 "Assoc-voc" = "Assoc-voc",
                 "Assoc-acdm" = "Assoc-acdm",
                 "Some-college" = "Some-college",
                 "Bachelors" = "Bachelors",
                 "Masters" = "Masters",
                 "Doctorate" = "Doctorate",
                 "Prof-school" = "Prof-school")),
   radioButtons("marital status", "Marital Status:",
                c("Married-spouse-absent" = "Married-spouse-absent",
                  "Married-civ-spouse" = "Married-civ-spouse",
                  "Married-AF-spouse" = "Married-AF-spouse",
                  "Divorced" = "Divorced",
                  "Never-married" = "Never-married",
                  "Separated" = "Separated",
                  "Widowed" = "Widowed")),
   selectInput("variable", "Occupation:",
               c("Adm-clerical" = "Adm-clerical",
                 "Armed-Forces" = "Armed-Forces",
                 "Craft-repair" = "Craft-repair",
                 "Exec-managerial" = "Exec-managerial",
                 "Farming-fishing" = "Farming-fishing",
                 "Handlers-cleaners" = "Handlers-cleaners",
                 "Machine-op-inspct" = "Machine-op-inspct",
                 "Other-service" = "Other-service",
                 "Priv-house-serv" = "Priv-house-serv",
                 "Prof-specialty" = "Prof-specialty",
                 "Protective-serv" = "Protective-serv",
                 "Sales" = "Sales",
                 "Tech-support" = "Tech-support",
                 "Transport-moving" = "Transport-moving")),
   selectInput("variable", "Relationship:",
               c("Husband" = "Husband",
                 "Not-in-family" = "Not-in-family",
                 "Other-relative" = "Other-relative",
                 "Own-child" = "Own-child",
                 "Unmarried" = "Unmarried",
                 "Wife" = "Wife")),
   checkboxGroupInput("variable", "Race",
                      c("Amer-Indian-Eskimo" = "Amer-Indian-Eskimo",
                        "Asian-Pac-Islander" = "Asian-Pac-Islander",
                        "Black" = "Black",
                        "Other" = "Other",
                        "White" = "White")),
   radioButtons("variable", "Sex",
                      c("Female" = "Female",
                        "Male" = "Male")),
   sliderInput("obs", "Capital Gain:",
               min = 0, max = 99999, value = 500),
   sliderInput("obs", "Capital Loss:",
               min = 0, max = 4356, value = 500),
   sliderInput("obs", "Hours Per Week:",
               min = 1, max = 99, value = 40),
   selectInput("variable", "Native Country Region:",
               c("Central-Asia" = "Central-Asia",
                 "East-Asia" = "East-Asia",
                 "Local gov" = "Local-gov",
                 "Never worked" = "Never-worked",
                 "Europe-East" = "Europe-East",
                 "Europe-West" = "Europe-West",
                 "North-America" = "North-America",
                 "South-America" = "South-America")),
  )
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)